#logging.level.org.apache.coyote.http11=debug
spring.messages.basename=messages,errors

# ?? ???? ??(?? 1800 -> 30?)
# ?? ???? ????? ??, ???? ?? ? ???? ?? ???? ?? ???? ??
# ?) 30??? ?? ???? ?? -> 9? 30?? ?? ?? ?? -> 9? 10?? ????? ??? -> ?? ?? 9? 40??? ??
server.servlet.session.timeout=60