spring.application.name=spring-mvc2-exception

# 오류 발생 시 whitelabel 기본 페이지 뜨지 않도록 설정
server.error.whitelabel.enabled=false

# BasicErrorController 기본 오류 페이지 경로
#server.error.path=/error

# 에러 메시지 응닶 값에 보이도록
server.error.include-message=always