spring.application.name=spring-mvc2-exception

# ?? ?? ??? ? ?? ? ??? whitelabel ?? ??? ???? ???? ??
server.error.whitelabel.enabled=false

# ?? ??? ??, ???? ?? ???? ??? ??? ?? ??? ??? BasicErrorController ?? ???? ??? ?? ??
#server.error.path=/error

